volumes:
  pg_data_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: on-failure
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: rodalen/foodgram_backend:latest
    depends_on: 
      - db
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
  frontend:
    image: rodalen/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: rodalen/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - db
      - backend
      - frontend
    ports:
      - 8080:90
    volumes:
      - static:/app/backend_static
      - media:/app/media